### ISSUE TITLE
1.18.5 -> 1.19.0

### ISSUE THREAD

**Issue by stephanedemotte** [greensock/GreenSock-JS#167]
Hi,

Since 1.19.0 import doest not work anymore :/

In 1.18.5
```
import TweenMax from 'gsap' // work fine
```

Now with 1.19.0
```
import TweenMax from 'gsap'
// give me this error
// Uncaught TypeError: _gsap2.default.staggerTo is not a function
```

Same for TweenMax.to, TweenMax.set etc.....

with 

```
require('gsap') // in 1.19.0 everything is fine...
```

But i have to change all my files...

For the moment i have lock Gsap to 1.18.5...

Any idea ?

Thanks !

**Comment by jackdoyle** [comment]
Hm, that's odd. I just tested it and it worked perfectly in 1.19.0 using: 
```javascript
import TweenMax from "gsap";
```
And it also works fine using the other syntax: 
```javascript
import { TweenMax } from "gsap";
```
That syntax also lets you reference multiple classes like:
```javascript 
import { TweenMax, Elastic, TimelineLite } from "gsap"; 
```
If you're still having trouble, would you please show me a reduced test case (like send me a project that I can compile where it's not working)? Are you using webpack?

**Comment by stephanedemotte** [comment]
Nope gulp/browserify (laravel elixir)

I will try to make more test, thanks !

**Comment by tylerxo** [comment]
I can also confirm this update broke my webpack build with a similar error.  I'll try to put together an isolated example when I get the time.

**Comment by deepsoul** [comment]
I can also confirm, that 1.19.0 broke the webpack build if you want to require some modules like TimeLineMax. If you did
`require('gsap')`
everything works fine. In version 1.18.5 the isolated import works!

**Comment by jackdoyle** [comment]
Very curious to see an example. Nobody seems to be able to provide one yet. I'm pretty sure there will be an easy fix but I'm just at a loss to offer one since I can't see how people were importing things, what their webpack config looked like, etc. 

Have you tried just defining the paths in your config file? I suspect that might resolve things here.
