### PR TITLE
Fix TypeScript case-sensitivity errors on case-insensitive filesystems

### LINKED ISSUE #637: 3.14.0 – TypeScript case-sensitivity issue with single-word module imports
After upgrading from 3.13.0 to 3.14.2, importing certain GSAP modules with a single-word name (e.g. Draggable, Observer) causes TypeScript to report a case-sensitivity error on case-sensitive file systems (macOS/Linux):

`import { Draggable } from 'gsap/Draggable'`

This results in the following error:

`File name ‘…/node_modules/gsap/types/Draggable.d.ts' differs from already included file name ‘…/node_modules/gsap/types/draggable.d.ts' only in casing.`

The error disappears when importing the module from the src path:

`import { Draggable } from 'gsap/src/Draggable'`

or by updating the reference in index.d.ts:

`<reference path="Draggable.d.ts"/>`

I don’t have extensive experience with this kind of TypeScript issue, so I’m not sure whether this is a problem on GSAP’s side or something related to my TypeScript configuration.

### PR DESCRIPTION
**Pull request by wietekepots-arch**
## Fix TypeScript case-sensitivity errors on case-insensitive filesystems

Fixes #637

### Problem

GSAP 3.14 causes TypeScript type-checking to fail on case-insensitive filesystems (macOS, Windows) when projects use `checkJs: true` in their `tsconfig.json`.

**Two issues were identified:**

#### 1. File casing mismatch (TS1149)

The type definition filenames use lowercase (`draggable.d.ts`), but the module declarations inside them use PascalCase (`declare module "gsap/Draggable"`). On case-insensitive filesystems, this causes:
```
error TS1149: File name 'node_modules/gsap/types/Draggable.d.ts' differs from
already included file name 'node_modules/gsap/types/draggable.d.ts' only in casing.
```

Affected files:
- `draggable.d.ts` → module `"gsap/Draggable"`
- `flip.d.ts` → module `"gsap/Flip"`
- `observer.d.ts` → module `"gsap/Observer"`

#### 2. Missing type annotations in VelocityTracker.js (TS7034/TS7006)

The `utils/VelocityTracker.js` file lacks type annotations. When consumers use `checkJs: true`, TypeScript attempts to type-check this file and produces ~60 implicit `any` errors.

Note: `skipLibCheck: true` only skips `.d.ts` files, not `.js` files.

### Solution

1. **Renamed type definition files** to match their corresponding JS files:
   - `types/draggable.d.ts` → `types/Draggable.d.ts`
   - `types/flip.d.ts` → `types/Flip.d.ts`
   - `types/observer.d.ts` → `types/Observer.d.ts`

2. **Updated references** in `types/index.d.ts` to use the new filenames

3. **Added `// @ts-nocheck`** to `VelocityTracker.js` (both `src/` and `esm/` versions) to prevent TypeScript from checking the untyped JS file. This is appropriate because types are already provided via `types/utils/velocity-tracker.d.ts`.

### Why this happens despite `node_modules` being excluded

`exclude` only affects direct compilation scope — it does NOT prevent TypeScript from resolving and checking types from packages you `import`. And `skipLibCheck: true` only skips `.d.ts` files, not `.js` files.

### Testing

After applying this fix, `tsc --noEmit` passes successfully on macOS.

### CODE REVIEW

**Comment by zaidkhanvmi** [comment]
has this issue  been resolved or i should work on this

**Comment by jackdoyle** [comment]
We already have it resolved in the next release so there's no "work" you need to do on it. If you just want to get it to work for you locally in the meantime, you can either change the case of the 3 files or you could edit the package.json file to remove the "exports" entirely.

**Comment by 0monish** [comment]
image

image
  
 I am still facing this issue.

**Review by codeCraft-Ritik — COMMENTED** [review]
Great fix! Resolving case-sensitivity issues and handling checkJs errors improves cross-platform TypeScript compatibility.
Nice approach with file renaming and @ts-nocheck for untyped JS 👍

**Review by codeCraft-Ritik — COMMENTED** [review]
Nice fix! Addressing both the casing mismatch and the checkJs issues should improve the experience for TypeScript users on macOS and Windows significantly. The root cause analysis is clear, and the proposed changes seem appropriately scoped.

**Comment by jackdoyle** [comment]
Already fixed, thanks!
