### ISSUE TITLE
Typescript 2.8.1 duplicate identifier "Animation"

### ISSUE THREAD

**Issue by ning-nolimitcity** [greensock/GreenSock-JS#257]
I am using Typescript and GASP in my project.
`"dependencies": {
    "@types/greensock": "^1.15.32",
    "gsap": "^1.20.4",
    "typescript":"^2.8.1"
  },
`
Yesterday when I update Typescript to 2.8.1, I got errors like:

`node_modules/@types/greensock/index.d.ts(49,15): error TS2300: Duplicate identifier 'Animation'.
node_modules/typescript/lib/lib.dom.d.ts(1691,11): error TS2300: Duplicate identifier 'Animation'.
node_modules/typescript/lib/lib.dom.d.ts(1711,13): error TS2300: Duplicate identifier 'Animation'.
`
In typescript/lib.dom.d.ts, they have added:

`interface Animation {
    currentTime: number | null;
    effect: AnimationEffectReadOnly;
    readonly finished: Promise<Animation>;
    id: string;
    readonly pending: boolean;
    readonly playState: "idle" | "running" | "paused" | "finished";
    playbackRate: number;
    readonly ready: Promise<Animation>;
    startTime: number;
    timeline: AnimationTimeline;
    cancel(): void;
    finish(): void;
    oncancel: (this: Animation, ev: AnimationPlaybackEvent) => any;
    onfinish: (this: Animation, ev: AnimationPlaybackEvent) => any;
    pause(): void;
    play(): void;
    reverse(): void;
}

declare var Animation: {
    prototype: Animation;
    new(effect?: AnimationEffectReadOnly, timeline?: AnimationTimeline): Animation;
};
`
Is there any suggestion to fix it? Thanks!

**Comment by jackdoyle** [comment]
Hm, I'm not sure - perhaps @OSUBlake can chime in (he's the resident Typescript expert - I'm totally unfamiliar with it).

**Comment by urgn** [comment]
@ning-nolimitcity try rollback your typescript version, it worked for me
``npm i tsc@2.4.1``

**Comment by kribblo** [comment]
> try rollback your typescript version

That's what we're doing, of course, but that's only a temporary measure as you'll want to have the newer versions in the future as bug fixes and features come in.

**Comment by clabough** [comment]
Best workaround is to edit the `@types/greensock/index.d.ts` file and do a search and replace. Replace `Animation` with `GS_Animation`

**Comment by clabough** [comment]
@ning-nolimitcity Try switching to `@types/gsap` then.

**Comment by ning-nolimitcity** [comment]
@types/gsap works! 
So we use gsap.TimelineLite instead of TimelineLite.
Great Thanks @clabough
